### ISSUE TITLE
Suggestions for more apps

### ISSUE THREAD

**Issue by MKCOOL142** [sysworx/Material-You-app-list#1]
https://github.com/libre-tube/LibreTube (sadly still extremely bare bones, lacking pretty much every feature so far)
https://github.com/KieronQuinn/DiscoverKiller
https://github.com/KieronQuinn/ClassicPowerMenu
https://github.com/KieronQuinn/TapTap
https://github.com/RetroMusicPlayer/RetroMusicPlayer

**Comment by echo-diogofernandes** [comment]
there's that one too:

https://f-droid.org/en/packages/org.oxycblt.auxio/

**Comment by SaschMie** [comment]
Thank you, i added them :)

**Comment by SaschMie** [comment]
Thank you, i added them to the list :)

**Comment by MKCOOL142** [comment]
Sync for Reddit also got material you now

**Comment by Naverim** [comment]
I got more suggestions
An RSS Reader: https://github.com/Ashinch/ReadYou
QR Code app:
https://play.google.com/store/apps/details?id=com.kokoschka.michael.qrtools
