### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Naverim** [sysworx/Material-You-app-list#2]
An RSS Reader: https://github.com/Ashinch/ReadYou
News app:
https://www.f-droid.org/packages/co.appreactor.news/
QR Code app:
https://play.google.com/store/apps/details?id=com.kokoschka.michael.qrtools
An F-Droid client
https://www.f-droid.org/packages/com.looker.droidify/
File manager
https://github.com/zhanghai/MaterialFiles
**Some apps that I think counts as Material You**
Bundled Notes https://play.google.com/store/apps/details?id=com.xaviertobin.noted
All-In-One Calculator https://play.google.com/store/apps/details?id=all.in.one.calculator
Periodic table https://play.google.com/store/apps/details?id=com.jlindemann.science

**Comment by KelvinCrag** [comment]
This list is gold.. thanks for the recommendations

**Comment by SaschMie** [comment]
Ty :) added them
