### ISSUE TITLE
Nekogram Telegram client

### ISSUE THREAD

**Issue by MKCOOL142** [sysworx/Material-You-app-list#3]
Nekogram (and other telegram clients that incorporated the feature as well like Owlgram f.e) recently introduced a theme that adapts to your material you colors scheme, does that still count since the rest of the app isn't following material you design guidelines that strictly apart from that theme

**Comment by txyyh** [comment]
Nagram also implemented this in latest release  [in there telegram channel](https://t.me/nagram_channel/475?single)

Here is a app that can generate tg theme for most Android tg clients, it can bring the same things to most telegram apps
https://github.com/c3r5b8/Telegram-Monet

And finally, the most Material You tg clients I have ever saw is [mdgram](https://t.me/mdmods_you). It's just great for MD3
