### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by neil3000** [sysworx/Material-You-app-list#4]
[Repainter, by (the incredible) kdrag0n](https://play.google.com/store/apps/details?id=dev.kdrag0n.dyntheme)

[Lawnchair, by David Sn](https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah)

[Counters, by Neïl Rahmouni](https://play.google.com/store/apps/details?id=rahmouni.neil.counters)

**Comment by SaschMie** [comment]
Ty :) added them
